// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cert.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// cert合约action
type CertAction struct {
	// Types that are valid to be assigned to Value:
	//	*CertAction_New
	//	*CertAction_Update
	//	*CertAction_Normal
	Value                isCertAction_Value `protobuf_oneof:"value"`
	Ty                   int32              `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CertAction) Reset()         { *m = CertAction{} }
func (m *CertAction) String() string { return proto.CompactTextString(m) }
func (*CertAction) ProtoMessage()    {}
func (*CertAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{0}
}

func (m *CertAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertAction.Unmarshal(m, b)
}
func (m *CertAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertAction.Marshal(b, m, deterministic)
}
func (m *CertAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertAction.Merge(m, src)
}
func (m *CertAction) XXX_Size() int {
	return xxx_messageInfo_CertAction.Size(m)
}
func (m *CertAction) XXX_DiscardUnknown() {
	xxx_messageInfo_CertAction.DiscardUnknown(m)
}

var xxx_messageInfo_CertAction proto.InternalMessageInfo

type isCertAction_Value interface {
	isCertAction_Value()
}

type CertAction_New struct {
	New *CertNew `protobuf:"bytes,1,opt,name=new,proto3,oneof"`
}

type CertAction_Update struct {
	Update *CertUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type CertAction_Normal struct {
	Normal *CertNormal `protobuf:"bytes,3,opt,name=normal,proto3,oneof"`
}

func (*CertAction_New) isCertAction_Value() {}

func (*CertAction_Update) isCertAction_Value() {}

func (*CertAction_Normal) isCertAction_Value() {}

func (m *CertAction) GetValue() isCertAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CertAction) GetNew() *CertNew {
	if x, ok := m.GetValue().(*CertAction_New); ok {
		return x.New
	}
	return nil
}

func (m *CertAction) GetUpdate() *CertUpdate {
	if x, ok := m.GetValue().(*CertAction_Update); ok {
		return x.Update
	}
	return nil
}

func (m *CertAction) GetNormal() *CertNormal {
	if x, ok := m.GetValue().(*CertAction_Normal); ok {
		return x.Normal
	}
	return nil
}

func (m *CertAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CertAction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CertAction_New)(nil),
		(*CertAction_Update)(nil),
		(*CertAction_Normal)(nil),
	}
}

// 证书启用
type CertNew struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertNew) Reset()         { *m = CertNew{} }
func (m *CertNew) String() string { return proto.CompactTextString(m) }
func (*CertNew) ProtoMessage()    {}
func (*CertNew) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{1}
}

func (m *CertNew) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertNew.Unmarshal(m, b)
}
func (m *CertNew) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertNew.Marshal(b, m, deterministic)
}
func (m *CertNew) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertNew.Merge(m, src)
}
func (m *CertNew) XXX_Size() int {
	return xxx_messageInfo_CertNew.Size(m)
}
func (m *CertNew) XXX_DiscardUnknown() {
	xxx_messageInfo_CertNew.DiscardUnknown(m)
}

var xxx_messageInfo_CertNew proto.InternalMessageInfo

func (m *CertNew) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CertNew) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// 证书更新
type CertUpdate struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertUpdate) Reset()         { *m = CertUpdate{} }
func (m *CertUpdate) String() string { return proto.CompactTextString(m) }
func (*CertUpdate) ProtoMessage()    {}
func (*CertUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{2}
}

func (m *CertUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertUpdate.Unmarshal(m, b)
}
func (m *CertUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertUpdate.Marshal(b, m, deterministic)
}
func (m *CertUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertUpdate.Merge(m, src)
}
func (m *CertUpdate) XXX_Size() int {
	return xxx_messageInfo_CertUpdate.Size(m)
}
func (m *CertUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CertUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CertUpdate proto.InternalMessageInfo

func (m *CertUpdate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CertUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// 用户证书校验
type CertNormal struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertNormal) Reset()         { *m = CertNormal{} }
func (m *CertNormal) String() string { return proto.CompactTextString(m) }
func (*CertNormal) ProtoMessage()    {}
func (*CertNormal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{3}
}

func (m *CertNormal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertNormal.Unmarshal(m, b)
}
func (m *CertNormal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertNormal.Marshal(b, m, deterministic)
}
func (m *CertNormal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertNormal.Merge(m, src)
}
func (m *CertNormal) XXX_Size() int {
	return xxx_messageInfo_CertNormal.Size(m)
}
func (m *CertNormal) XXX_DiscardUnknown() {
	xxx_messageInfo_CertNormal.DiscardUnknown(m)
}

var xxx_messageInfo_CertNormal proto.InternalMessageInfo

func (m *CertNormal) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CertNormal) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CertSignature struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Cert                 []byte   `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Uid                  []byte   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertSignature) Reset()         { *m = CertSignature{} }
func (m *CertSignature) String() string { return proto.CompactTextString(m) }
func (*CertSignature) ProtoMessage()    {}
func (*CertSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{4}
}

func (m *CertSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertSignature.Unmarshal(m, b)
}
func (m *CertSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertSignature.Marshal(b, m, deterministic)
}
func (m *CertSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertSignature.Merge(m, src)
}
func (m *CertSignature) XXX_Size() int {
	return xxx_messageInfo_CertSignature.Size(m)
}
func (m *CertSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_CertSignature.DiscardUnknown(m)
}

var xxx_messageInfo_CertSignature proto.InternalMessageInfo

func (m *CertSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CertSignature) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *CertSignature) GetUid() []byte {
	if m != nil {
		return m.Uid
	}
	return nil
}

// 用户注册请求
type ReqRegisterUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Admin                string   `protobuf:"bytes,4,opt,name=admin,proto3" json:"admin,omitempty"`
	Sign                 []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegisterUser) Reset()         { *m = ReqRegisterUser{} }
func (m *ReqRegisterUser) String() string { return proto.CompactTextString(m) }
func (*ReqRegisterUser) ProtoMessage()    {}
func (*ReqRegisterUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{5}
}

func (m *ReqRegisterUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegisterUser.Unmarshal(m, b)
}
func (m *ReqRegisterUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegisterUser.Marshal(b, m, deterministic)
}
func (m *ReqRegisterUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegisterUser.Merge(m, src)
}
func (m *ReqRegisterUser) XXX_Size() int {
	return xxx_messageInfo_ReqRegisterUser.Size(m)
}
func (m *ReqRegisterUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegisterUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegisterUser proto.InternalMessageInfo

func (m *ReqRegisterUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRegisterUser) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqRegisterUser) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *ReqRegisterUser) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *ReqRegisterUser) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 用户注销请求
type ReqRevokeUser struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Admin                string   `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRevokeUser) Reset()         { *m = ReqRevokeUser{} }
func (m *ReqRevokeUser) String() string { return proto.CompactTextString(m) }
func (*ReqRevokeUser) ProtoMessage()    {}
func (*ReqRevokeUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{6}
}

func (m *ReqRevokeUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRevokeUser.Unmarshal(m, b)
}
func (m *ReqRevokeUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRevokeUser.Marshal(b, m, deterministic)
}
func (m *ReqRevokeUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRevokeUser.Merge(m, src)
}
func (m *ReqRevokeUser) XXX_Size() int {
	return xxx_messageInfo_ReqRevokeUser.Size(m)
}
func (m *ReqRevokeUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRevokeUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRevokeUser proto.InternalMessageInfo

func (m *ReqRevokeUser) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqRevokeUser) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *ReqRevokeUser) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 申请证书
type ReqEnroll struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Admin                string   `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEnroll) Reset()         { *m = ReqEnroll{} }
func (m *ReqEnroll) String() string { return proto.CompactTextString(m) }
func (*ReqEnroll) ProtoMessage()    {}
func (*ReqEnroll) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{7}
}

func (m *ReqEnroll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnroll.Unmarshal(m, b)
}
func (m *ReqEnroll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnroll.Marshal(b, m, deterministic)
}
func (m *ReqEnroll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnroll.Merge(m, src)
}
func (m *ReqEnroll) XXX_Size() int {
	return xxx_messageInfo_ReqEnroll.Size(m)
}
func (m *ReqEnroll) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnroll.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnroll proto.InternalMessageInfo

func (m *ReqEnroll) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqEnroll) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *ReqEnroll) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 证书信息
type RepEnroll struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Cert                 []byte   `protobuf:"bytes,2,opt,name=cert,proto3" json:"cert,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepEnroll) Reset()         { *m = RepEnroll{} }
func (m *RepEnroll) String() string { return proto.CompactTextString(m) }
func (*RepEnroll) ProtoMessage()    {}
func (*RepEnroll) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{8}
}

func (m *RepEnroll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepEnroll.Unmarshal(m, b)
}
func (m *RepEnroll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepEnroll.Marshal(b, m, deterministic)
}
func (m *RepEnroll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepEnroll.Merge(m, src)
}
func (m *RepEnroll) XXX_Size() int {
	return xxx_messageInfo_RepEnroll.Size(m)
}
func (m *RepEnroll) XXX_DiscardUnknown() {
	xxx_messageInfo_RepEnroll.DiscardUnknown(m)
}

var xxx_messageInfo_RepEnroll proto.InternalMessageInfo

func (m *RepEnroll) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *RepEnroll) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *RepEnroll) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// 证书注销请求
type ReqRevokeCert struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Admin                string   `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	Sign                 []byte   `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRevokeCert) Reset()         { *m = ReqRevokeCert{} }
func (m *ReqRevokeCert) String() string { return proto.CompactTextString(m) }
func (*ReqRevokeCert) ProtoMessage()    {}
func (*ReqRevokeCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{9}
}

func (m *ReqRevokeCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRevokeCert.Unmarshal(m, b)
}
func (m *ReqRevokeCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRevokeCert.Marshal(b, m, deterministic)
}
func (m *ReqRevokeCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRevokeCert.Merge(m, src)
}
func (m *ReqRevokeCert) XXX_Size() int {
	return xxx_messageInfo_ReqRevokeCert.Size(m)
}
func (m *ReqRevokeCert) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRevokeCert.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRevokeCert proto.InternalMessageInfo

func (m *ReqRevokeCert) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *ReqRevokeCert) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqRevokeCert) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *ReqRevokeCert) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 用户信息
type CAUserItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	RawKey               []byte   `protobuf:"bytes,5,opt,name=rawKey,proto3" json:"rawKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CAUserItem) Reset()         { *m = CAUserItem{} }
func (m *CAUserItem) String() string { return proto.CompactTextString(m) }
func (*CAUserItem) ProtoMessage()    {}
func (*CAUserItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{10}
}

func (m *CAUserItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CAUserItem.Unmarshal(m, b)
}
func (m *CAUserItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CAUserItem.Marshal(b, m, deterministic)
}
func (m *CAUserItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CAUserItem.Merge(m, src)
}
func (m *CAUserItem) XXX_Size() int {
	return xxx_messageInfo_CAUserItem.Size(m)
}
func (m *CAUserItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CAUserItem.DiscardUnknown(m)
}

var xxx_messageInfo_CAUserItem proto.InternalMessageInfo

func (m *CAUserItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CAUserItem) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *CAUserItem) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *CAUserItem) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *CAUserItem) GetRawKey() []byte {
	if m != nil {
		return m.RawKey
	}
	return nil
}

// 用户信息列表
type CAUsers struct {
	Users                []*CAUserItem `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CAUsers) Reset()         { *m = CAUsers{} }
func (m *CAUsers) String() string { return proto.CompactTextString(m) }
func (*CAUsers) ProtoMessage()    {}
func (*CAUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{11}
}

func (m *CAUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CAUsers.Unmarshal(m, b)
}
func (m *CAUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CAUsers.Marshal(b, m, deterministic)
}
func (m *CAUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CAUsers.Merge(m, src)
}
func (m *CAUsers) XXX_Size() int {
	return xxx_messageInfo_CAUsers.Size(m)
}
func (m *CAUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_CAUsers.DiscardUnknown(m)
}

var xxx_messageInfo_CAUsers proto.InternalMessageInfo

func (m *CAUsers) GetUsers() []*CAUserItem {
	if m != nil {
		return m.Users
	}
	return nil
}

// 证书信息
type CertStoreItem struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ExipreTime           int64    `protobuf:"varint,3,opt,name=exipreTime,proto3" json:"exipreTime,omitempty"`
	RevokeTime           int64    `protobuf:"varint,4,opt,name=revokeTime,proto3" json:"revokeTime,omitempty"`
	Cert                 []byte   `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`
	Identity             string   `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertStoreItem) Reset()         { *m = CertStoreItem{} }
func (m *CertStoreItem) String() string { return proto.CompactTextString(m) }
func (*CertStoreItem) ProtoMessage()    {}
func (*CertStoreItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{12}
}

func (m *CertStoreItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertStoreItem.Unmarshal(m, b)
}
func (m *CertStoreItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertStoreItem.Marshal(b, m, deterministic)
}
func (m *CertStoreItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertStoreItem.Merge(m, src)
}
func (m *CertStoreItem) XXX_Size() int {
	return xxx_messageInfo_CertStoreItem.Size(m)
}
func (m *CertStoreItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CertStoreItem.DiscardUnknown(m)
}

var xxx_messageInfo_CertStoreItem proto.InternalMessageInfo

func (m *CertStoreItem) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *CertStoreItem) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CertStoreItem) GetExipreTime() int64 {
	if m != nil {
		return m.ExipreTime
	}
	return 0
}

func (m *CertStoreItem) GetRevokeTime() int64 {
	if m != nil {
		return m.RevokeTime
	}
	return 0
}

func (m *CertStoreItem) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *CertStoreItem) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

// 获取CRL请求
type ReqGetCRL struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetCRL) Reset()         { *m = ReqGetCRL{} }
func (m *ReqGetCRL) String() string { return proto.CompactTextString(m) }
func (*ReqGetCRL) ProtoMessage()    {}
func (*ReqGetCRL) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{13}
}

func (m *ReqGetCRL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetCRL.Unmarshal(m, b)
}
func (m *ReqGetCRL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetCRL.Marshal(b, m, deterministic)
}
func (m *ReqGetCRL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetCRL.Merge(m, src)
}
func (m *ReqGetCRL) XXX_Size() int {
	return xxx_messageInfo_ReqGetCRL.Size(m)
}
func (m *ReqGetCRL) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetCRL.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetCRL proto.InternalMessageInfo

func (m *ReqGetCRL) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqGetCRL) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 获取CRL响应
type RepGetCRL struct {
	Crl                  []byte   `protobuf:"bytes,1,opt,name=crl,proto3" json:"crl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepGetCRL) Reset()         { *m = RepGetCRL{} }
func (m *RepGetCRL) String() string { return proto.CompactTextString(m) }
func (*RepGetCRL) ProtoMessage()    {}
func (*RepGetCRL) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{14}
}

func (m *RepGetCRL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepGetCRL.Unmarshal(m, b)
}
func (m *RepGetCRL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepGetCRL.Marshal(b, m, deterministic)
}
func (m *RepGetCRL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepGetCRL.Merge(m, src)
}
func (m *RepGetCRL) XXX_Size() int {
	return xxx_messageInfo_RepGetCRL.Size(m)
}
func (m *RepGetCRL) XXX_DiscardUnknown() {
	xxx_messageInfo_RepGetCRL.DiscardUnknown(m)
}

var xxx_messageInfo_RepGetCRL proto.InternalMessageInfo

func (m *RepGetCRL) GetCrl() []byte {
	if m != nil {
		return m.Crl
	}
	return nil
}

// revoke证书sn存储列表
type RevokeStore struct {
	Serial               []string `protobuf:"bytes,1,rep,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeStore) Reset()         { *m = RevokeStore{} }
func (m *RevokeStore) String() string { return proto.CompactTextString(m) }
func (*RevokeStore) ProtoMessage()    {}
func (*RevokeStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{15}
}

func (m *RevokeStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeStore.Unmarshal(m, b)
}
func (m *RevokeStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeStore.Marshal(b, m, deterministic)
}
func (m *RevokeStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeStore.Merge(m, src)
}
func (m *RevokeStore) XXX_Size() int {
	return xxx_messageInfo_RevokeStore.Size(m)
}
func (m *RevokeStore) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeStore.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeStore proto.InternalMessageInfo

func (m *RevokeStore) GetSerial() []string {
	if m != nil {
		return m.Serial
	}
	return nil
}

// 获取用户信息
type ReqGetUserInfo struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetUserInfo) Reset()         { *m = ReqGetUserInfo{} }
func (m *ReqGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*ReqGetUserInfo) ProtoMessage()    {}
func (*ReqGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{16}
}

func (m *ReqGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetUserInfo.Unmarshal(m, b)
}
func (m *ReqGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetUserInfo.Marshal(b, m, deterministic)
}
func (m *ReqGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetUserInfo.Merge(m, src)
}
func (m *ReqGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_ReqGetUserInfo.Size(m)
}
func (m *ReqGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetUserInfo proto.InternalMessageInfo

func (m *ReqGetUserInfo) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *ReqGetUserInfo) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 返回用户信息
type RepGetUserInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Serial               string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepGetUserInfo) Reset()         { *m = RepGetUserInfo{} }
func (m *RepGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*RepGetUserInfo) ProtoMessage()    {}
func (*RepGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{17}
}

func (m *RepGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepGetUserInfo.Unmarshal(m, b)
}
func (m *RepGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepGetUserInfo.Marshal(b, m, deterministic)
}
func (m *RepGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepGetUserInfo.Merge(m, src)
}
func (m *RepGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_RepGetUserInfo.Size(m)
}
func (m *RepGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepGetUserInfo proto.InternalMessageInfo

func (m *RepGetUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RepGetUserInfo) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *RepGetUserInfo) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *RepGetUserInfo) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

// 根据序列号查询证书
type ReqGetCertInfo struct {
	Sn                   string   `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetCertInfo) Reset()         { *m = ReqGetCertInfo{} }
func (m *ReqGetCertInfo) String() string { return proto.CompactTextString(m) }
func (*ReqGetCertInfo) ProtoMessage()    {}
func (*ReqGetCertInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{18}
}

func (m *ReqGetCertInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetCertInfo.Unmarshal(m, b)
}
func (m *ReqGetCertInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetCertInfo.Marshal(b, m, deterministic)
}
func (m *ReqGetCertInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetCertInfo.Merge(m, src)
}
func (m *ReqGetCertInfo) XXX_Size() int {
	return xxx_messageInfo_ReqGetCertInfo.Size(m)
}
func (m *ReqGetCertInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetCertInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetCertInfo proto.InternalMessageInfo

func (m *ReqGetCertInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *ReqGetCertInfo) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 返回证书信息
type RepGetCertInfo struct {
	Serial               string   `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ExipreTime           int64    `protobuf:"varint,3,opt,name=exipreTime,proto3" json:"exipreTime,omitempty"`
	RevokeTime           int64    `protobuf:"varint,4,opt,name=revokeTime,proto3" json:"revokeTime,omitempty"`
	Cert                 []byte   `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`
	Identity             string   `protobuf:"bytes,6,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepGetCertInfo) Reset()         { *m = RepGetCertInfo{} }
func (m *RepGetCertInfo) String() string { return proto.CompactTextString(m) }
func (*RepGetCertInfo) ProtoMessage()    {}
func (*RepGetCertInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{19}
}

func (m *RepGetCertInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepGetCertInfo.Unmarshal(m, b)
}
func (m *RepGetCertInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepGetCertInfo.Marshal(b, m, deterministic)
}
func (m *RepGetCertInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepGetCertInfo.Merge(m, src)
}
func (m *RepGetCertInfo) XXX_Size() int {
	return xxx_messageInfo_RepGetCertInfo.Size(m)
}
func (m *RepGetCertInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RepGetCertInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RepGetCertInfo proto.InternalMessageInfo

func (m *RepGetCertInfo) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *RepGetCertInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RepGetCertInfo) GetExipreTime() int64 {
	if m != nil {
		return m.ExipreTime
	}
	return 0
}

func (m *RepGetCertInfo) GetRevokeTime() int64 {
	if m != nil {
		return m.RevokeTime
	}
	return 0
}

func (m *RepGetCertInfo) GetCert() []byte {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *RepGetCertInfo) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

// 添加删除CA服务管理员
type ReqAdmin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAdmin) Reset()         { *m = ReqAdmin{} }
func (m *ReqAdmin) String() string { return proto.CompactTextString(m) }
func (*ReqAdmin) ProtoMessage()    {}
func (*ReqAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{20}
}

func (m *ReqAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAdmin.Unmarshal(m, b)
}
func (m *ReqAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAdmin.Marshal(b, m, deterministic)
}
func (m *ReqAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAdmin.Merge(m, src)
}
func (m *ReqAdmin) XXX_Size() int {
	return xxx_messageInfo_ReqAdmin.Size(m)
}
func (m *ReqAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAdmin proto.InternalMessageInfo

func (m *ReqAdmin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAdmin) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *ReqAdmin) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// 管理员信息
type AdminStore struct {
	Admins               []*CAUserItem `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AdminStore) Reset()         { *m = AdminStore{} }
func (m *AdminStore) String() string { return proto.CompactTextString(m) }
func (*AdminStore) ProtoMessage()    {}
func (*AdminStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{21}
}

func (m *AdminStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminStore.Unmarshal(m, b)
}
func (m *AdminStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminStore.Marshal(b, m, deterministic)
}
func (m *AdminStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminStore.Merge(m, src)
}
func (m *AdminStore) XXX_Size() int {
	return xxx_messageInfo_AdminStore.Size(m)
}
func (m *AdminStore) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminStore.DiscardUnknown(m)
}

var xxx_messageInfo_AdminStore proto.InternalMessageInfo

func (m *AdminStore) GetAdmins() []*CAUserItem {
	if m != nil {
		return m.Admins
	}
	return nil
}

// 证书校验请求
type ReqValidateCert struct {
	Serials              []string `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqValidateCert) Reset()         { *m = ReqValidateCert{} }
func (m *ReqValidateCert) String() string { return proto.CompactTextString(m) }
func (*ReqValidateCert) ProtoMessage()    {}
func (*ReqValidateCert) Descriptor() ([]byte, []int) {
	return fileDescriptor_a142e29cbef9b1cf, []int{22}
}

func (m *ReqValidateCert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqValidateCert.Unmarshal(m, b)
}
func (m *ReqValidateCert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqValidateCert.Marshal(b, m, deterministic)
}
func (m *ReqValidateCert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqValidateCert.Merge(m, src)
}
func (m *ReqValidateCert) XXX_Size() int {
	return xxx_messageInfo_ReqValidateCert.Size(m)
}
func (m *ReqValidateCert) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqValidateCert.DiscardUnknown(m)
}

var xxx_messageInfo_ReqValidateCert proto.InternalMessageInfo

func (m *ReqValidateCert) GetSerials() []string {
	if m != nil {
		return m.Serials
	}
	return nil
}

func init() {
	proto.RegisterType((*CertAction)(nil), "types.CertAction")
	proto.RegisterType((*CertNew)(nil), "types.CertNew")
	proto.RegisterType((*CertUpdate)(nil), "types.CertUpdate")
	proto.RegisterType((*CertNormal)(nil), "types.CertNormal")
	proto.RegisterType((*CertSignature)(nil), "types.CertSignature")
	proto.RegisterType((*ReqRegisterUser)(nil), "types.ReqRegisterUser")
	proto.RegisterType((*ReqRevokeUser)(nil), "types.ReqRevokeUser")
	proto.RegisterType((*ReqEnroll)(nil), "types.ReqEnroll")
	proto.RegisterType((*RepEnroll)(nil), "types.RepEnroll")
	proto.RegisterType((*ReqRevokeCert)(nil), "types.ReqRevokeCert")
	proto.RegisterType((*CAUserItem)(nil), "types.CAUserItem")
	proto.RegisterType((*CAUsers)(nil), "types.CAUsers")
	proto.RegisterType((*CertStoreItem)(nil), "types.CertStoreItem")
	proto.RegisterType((*ReqGetCRL)(nil), "types.ReqGetCRL")
	proto.RegisterType((*RepGetCRL)(nil), "types.RepGetCRL")
	proto.RegisterType((*RevokeStore)(nil), "types.RevokeStore")
	proto.RegisterType((*ReqGetUserInfo)(nil), "types.ReqGetUserInfo")
	proto.RegisterType((*RepGetUserInfo)(nil), "types.RepGetUserInfo")
	proto.RegisterType((*ReqGetCertInfo)(nil), "types.ReqGetCertInfo")
	proto.RegisterType((*RepGetCertInfo)(nil), "types.RepGetCertInfo")
	proto.RegisterType((*ReqAdmin)(nil), "types.ReqAdmin")
	proto.RegisterType((*AdminStore)(nil), "types.AdminStore")
	proto.RegisterType((*ReqValidateCert)(nil), "types.ReqValidateCert")
}

func init() { proto.RegisterFile("cert.proto", fileDescriptor_a142e29cbef9b1cf) }

var fileDescriptor_a142e29cbef9b1cf = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x51, 0x4f, 0xd4, 0x40,
	0x10, 0xa6, 0xed, 0xb5, 0xc7, 0x0d, 0xc7, 0x89, 0x1b, 0x43, 0x1a, 0xa3, 0x86, 0x6c, 0x62, 0xc4,
	0x90, 0x90, 0x88, 0x24, 0x3e, 0xf8, 0x22, 0x12, 0x23, 0xa8, 0x21, 0x71, 0x11, 0xdf, 0x0b, 0x37,
	0x92, 0x86, 0x5e, 0x5b, 0xb6, 0x5b, 0xf0, 0x9e, 0xf5, 0x9f, 0xf8, 0x03, 0xf4, 0x27, 0x9a, 0x99,
	0xdd, 0xde, 0x15, 0x39, 0x50, 0x12, 0x4d, 0x7c, 0xdb, 0xe9, 0xcc, 0x7c, 0xfb, 0xed, 0xf7, 0xcd,
	0x6e, 0x01, 0x8e, 0x50, 0x9b, 0xf5, 0x52, 0x17, 0xa6, 0x10, 0xa1, 0x19, 0x97, 0x58, 0xc9, 0x6f,
	0x1e, 0xc0, 0x36, 0x6a, 0xb3, 0x75, 0x64, 0xd2, 0x22, 0x17, 0x12, 0x82, 0x1c, 0xcf, 0x63, 0x6f,
	0xc5, 0x5b, 0x5d, 0xd8, 0x18, 0xac, 0x73, 0xcd, 0x3a, 0xe5, 0xf7, 0xf0, 0x7c, 0x67, 0x4e, 0x51,
	0x52, 0xac, 0x41, 0x54, 0x97, 0xc3, 0xc4, 0x60, 0xec, 0x73, 0xd9, 0xed, 0x56, 0xd9, 0x01, 0x27,
	0x76, 0xe6, 0x94, 0x2b, 0xa1, 0xe2, 0xbc, 0xd0, 0xa3, 0x24, 0x8b, 0x83, 0x4b, 0xc5, 0x7b, 0x9c,
	0xa0, 0x62, 0x5b, 0x22, 0x06, 0xe0, 0x9b, 0x71, 0xdc, 0x59, 0xf1, 0x56, 0x43, 0xe5, 0x9b, 0xf1,
	0xcb, 0x2e, 0x84, 0x67, 0x49, 0x56, 0xa3, 0x7c, 0x02, 0x5d, 0x47, 0x42, 0x2c, 0x41, 0x70, 0x82,
	0x63, 0x66, 0xd8, 0x53, 0xb4, 0x14, 0x77, 0x5c, 0x15, 0xd3, 0xe9, 0x2b, 0xd7, 0xb2, 0x69, 0xcf,
	0x65, 0x09, 0xdd, 0xb4, 0xcb, 0x32, 0xfb, 0xe3, 0xae, 0x7d, 0x58, 0xa4, 0xae, 0xfd, 0xf4, 0x38,
	0x4f, 0x4c, 0xad, 0x51, 0xdc, 0x83, 0x5e, 0xd5, 0x04, 0xdc, 0xde, 0x57, 0xd3, 0x0f, 0x42, 0x40,
	0x87, 0x8c, 0x70, 0x18, 0xbc, 0xa6, 0xad, 0xea, 0x74, 0xc8, 0x22, 0xf5, 0x15, 0x2d, 0xe5, 0x17,
	0x0f, 0x6e, 0x29, 0x3c, 0x55, 0x78, 0x9c, 0x56, 0x06, 0xf5, 0x41, 0x85, 0x9a, 0x3a, 0xf3, 0x64,
	0x84, 0x8e, 0x11, 0xaf, 0xc5, 0x5d, 0x98, 0x4f, 0x87, 0x98, 0x9b, 0xd4, 0x8c, 0x19, 0xb1, 0xa7,
	0x26, 0xb1, 0x58, 0x86, 0xa8, 0xac, 0x0f, 0xdf, 0xe2, 0x98, 0x81, 0x7b, 0xca, 0x45, 0x74, 0x8c,
	0x64, 0x38, 0x4a, 0x73, 0xd6, 0xba, 0xa7, 0x6c, 0x40, 0xe8, 0x44, 0x32, 0x0e, 0x2d, 0x2f, 0x5a,
	0xcb, 0x03, 0x58, 0x64, 0x12, 0x67, 0xc5, 0x09, 0x32, 0x85, 0xf6, 0x76, 0xde, 0x2f, 0xdb, 0x4d,
	0x60, 0xfd, 0x59, 0xb0, 0x41, 0x0b, 0xf6, 0x3d, 0xf4, 0x14, 0x9e, 0xbe, 0xca, 0x75, 0x91, 0x65,
	0x7f, 0x09, 0x72, 0x97, 0x20, 0x4b, 0x07, 0xb9, 0x0c, 0x51, 0x85, 0x3a, 0x4d, 0x32, 0x07, 0xe8,
	0xa2, 0xab, 0xa4, 0x3f, 0x71, 0x0a, 0xf5, 0xd9, 0x65, 0x39, 0x6a, 0x1d, 0x9a, 0x8c, 0xbd, 0x12,
	0xee, 0x3a, 0xed, 0x27, 0xcc, 0x83, 0x59, 0xcc, 0x3b, 0x2d, 0xe6, 0x5f, 0xe9, 0x0e, 0x6e, 0x91,
	0xba, 0xbb, 0x06, 0x47, 0x33, 0x4d, 0x9e, 0x1a, 0x69, 0x99, 0x37, 0x46, 0xb6, 0x09, 0x04, 0x97,
	0xcd, 0x77, 0xa4, 0x3b, 0x17, 0x48, 0x2f, 0x43, 0xa4, 0x93, 0x73, 0xc2, 0xb2, 0x46, 0xbb, 0x48,
	0x6e, 0x40, 0xd7, 0xb2, 0xa8, 0xc4, 0x23, 0x08, 0x6b, 0x5a, 0xc4, 0xde, 0x4a, 0xd0, 0xbe, 0xb4,
	0x13, 0x92, 0xca, 0xe6, 0xe5, 0x77, 0xcf, 0x8d, 0xbe, 0x29, 0x34, 0x32, 0xfb, 0xab, 0xa4, 0xa2,
	0xef, 0x26, 0x31, 0x75, 0xc5, 0x27, 0x08, 0x95, 0x8b, 0xc4, 0x03, 0x00, 0xfc, 0x9c, 0x96, 0x1a,
	0x3f, 0xa4, 0x23, 0xe4, 0x33, 0x04, 0xaa, 0xf5, 0x85, 0xf2, 0x9a, 0x8d, 0xe0, 0x7c, 0xc7, 0xe6,
	0xa7, 0x5f, 0x26, 0x8e, 0x86, 0x2d, 0x47, 0xdb, 0xaa, 0x44, 0x17, 0x55, 0x91, 0xcf, 0x79, 0xf2,
	0x5e, 0xa3, 0xd9, 0x56, 0xef, 0xae, 0x9d, 0xbc, 0xc6, 0x29, 0xbf, 0xe5, 0xd4, 0x7d, 0x9e, 0x31,
	0xd7, 0xbc, 0x04, 0xc1, 0x91, 0xce, 0xdc, 0xf5, 0xa6, 0xa5, 0x7c, 0x08, 0x0b, 0x76, 0x68, 0x58,
	0x8e, 0x0b, 0x52, 0x04, 0x53, 0x29, 0xe4, 0x0b, 0x18, 0x58, 0x0a, 0xac, 0x66, 0xfe, 0xa9, 0xb8,
	0x31, 0x8f, 0x92, 0x10, 0xca, 0x36, 0xc2, 0x3f, 0x1e, 0x1a, 0xb9, 0xd9, 0x70, 0x26, 0xb7, 0x79,
	0xc7, 0x01, 0xf8, 0x55, 0xee, 0xf6, 0xf3, 0xab, 0x7c, 0x26, 0xcf, 0x1f, 0x5e, 0x43, 0x74, 0xd2,
	0xf6, 0xbf, 0xcf, 0xc7, 0x1b, 0x98, 0x57, 0x78, 0xba, 0xd5, 0x5c, 0xd6, 0xdf, 0x88, 0x3a, 0x7d,
	0x52, 0x67, 0x3d, 0x49, 0xcf, 0x00, 0x18, 0xc8, 0x8e, 0xc3, 0x63, 0x88, 0xf8, 0x0d, 0xb8, 0xe6,
	0x56, 0xb9, 0x02, 0xb9, 0xc6, 0x4f, 0xff, 0xc7, 0x24, 0x4b, 0xe9, 0xef, 0xc5, 0x4f, 0x50, 0x0c,
	0x5d, 0xab, 0x54, 0xe5, 0xa6, 0xa9, 0x09, 0x0f, 0x23, 0xfe, 0xa1, 0x3f, 0xfd, 0x19, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x8c, 0x61, 0x46, 0xde, 0x07, 0x00, 0x00,
}
